# Generated by Django 4.2.3 on 2023-08-09 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Optional. Enter your first name', max_length=50)),
                ('last_name', models.CharField(blank=True, help_text='Optional. Enter your last name', max_length=50)),
                ('about_me', models.TextField(blank=True, help_text='Optional. Tell us about yourself', max_length=500)),
                ('profile_pic', models.ImageField(blank=True, help_text='Optional. Upload a profile picture', upload_to='profile_pics')),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('private', models.BooleanField(default=False, help_text='If checked, your profile will not be visible to other users')),
                ('friends', models.ManyToManyField(blank=True, help_text='Select the users you want to be friends with', related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
