# Generated by Django 4.2.3 on 2023-08-09 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Enter any notes you have about this genre', max_length=500)),
                ('number_of_books_read', models.PositiveIntegerField(default=0)),
                ('favourite', models.BooleanField(default=False, help_text='Is this one of your favourite genres?')),
                ('genre', models.ForeignKey(help_text='Select the genre', on_delete=django.db.models.deletion.CASCADE, to='books.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
