# Generated by Django 4.2.3 on 2023-08-09 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mybooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareBookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('reject_reason', models.TextField(blank=True, help_text='Enter a reason for rejecting the request', max_length=280)),
                ('book', models.ForeignKey(help_text='Select a book to share', on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('borrower', models.ForeignKey(help_text='Select a user to share with', on_delete=django.db.models.deletion.CASCADE, related_name='borrower_request', to=settings.AUTH_USER_MODEL)),
                ('loaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loaner_request', to=settings.AUTH_USER_MODEL)),
                ('shelf_book', models.ForeignKey(help_text='Select a book to share', on_delete=django.db.models.deletion.CASCADE, to='mybooks.mybook')),
            ],
            options={
                'ordering': ['-date_requested'],
            },
        ),
        migrations.CreateModel(
            name='ShareBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_alt', models.CharField(blank=True, help_text='Enter a name to share with a non-user', max_length=100)),
                ('date_shared', models.DateField(blank=True, help_text="Date shared. Leave blank to use today's date", null=True)),
                ('date_returned', models.DateField(blank=True, help_text="Date returned. Leave blank to use today's date", null=True)),
                ('returned', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Enter any notes about the loan', max_length=280)),
                ('book', models.ForeignKey(help_text='Select a book to share', on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('borrower', models.ForeignKey(blank=True, help_text='Select a user to share with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to=settings.AUTH_USER_MODEL)),
                ('loaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loaner', to=settings.AUTH_USER_MODEL)),
                ('shelf_book', models.ForeignKey(help_text='Select a book to share', on_delete=django.db.models.deletion.CASCADE, to='mybooks.mybook')),
            ],
            options={
                'ordering': ['-date_shared'],
            },
        ),
    ]
