# Generated by Django 4.2.3 on 2023-08-09 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, help_text='Enter a brief description of the book', max_length=500)),
                ('unread', models.BooleanField(default=True, help_text='Have you read this book?')),
                ('started_reading_on', models.DateField(blank=True, help_text='When did you start reading this book?', null=True)),
                ('currently_reading', models.BooleanField(default=False, help_text='Are you currently reading this book?')),
                ('abandoned', models.BooleanField(default=False, help_text='Have you abandoned this book? If so, maybe leave a note as to why.')),
                ('finished_reading_on', models.DateField(blank=True, help_text="When did you finish reading this book? If blank, today's date will be used.", null=True)),
                ('finished', models.BooleanField(default=False, help_text='Have you finished reading this book?')),
                ('restarted', models.BooleanField(default=False, help_text='Have you restarted reading this book?')),
                ('favourite', models.BooleanField(default=False, help_text='Is this one of your favourite books?')),
                ('notes', models.TextField(blank=True, help_text='Enter any notes you have about this book', max_length=500)),
                ('private', models.BooleanField(default=False, help_text="Book won't be visible to others on your shelf")),
                ('pages_total', models.PositiveIntegerField(default=0, help_text='How many pages are there in total?')),
                ('pages_read', models.PositiveIntegerField(default=0, help_text='How many pages have you read?')),
                ('number_of_times_read', models.PositiveIntegerField(default=0, help_text='How many times have you read this book?')),
                ('percentage_read', models.PositiveIntegerField(default=0)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(help_text='Select the book', on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
